---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.69.0_Linux-64bit.deb

script:
  - hugo -s ./site/

deploy:
  - provider: script
    script: bash ./deploy.sh
    skip_cleanup: true
    on:
      branch: develop
