baseURL = "https://anudeepsamaiya.github.io/"
languageCode = "en-us"
title = "Anudeep Samaiya"
# title = "in a brown study"
theme = "noteworthy"
publishDir = "../docs"
author = "Anudeep Samaiya"
license = "MIT"
licenselink = "https://github.com/anudeepsamaiya/anudeepsamaiya.com/blob/master/LICENSE"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/anudeepsamaiya/"
    weight = 1

[[menu.main]]
    identifier = "reading"
    name = "Reading"
    url = "/reading/"
    weight = 1.1

# [[menu.main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags/"
#     weight = 2
#
# [[menu.main]]
#     identifier = "archives"
#     name = "Archives"
#     url = "/archives/"
#     weight = 3

[params]
    enableEmoji = true
    math = true
    description = "Technical and not-so-technical writings."
    github   = "//github.com/anudeepsamaiya"
    twitter  = "//twitter.com/anudeepsamaiya"
    stackoverflow = "//stackoverflow.com/users/2079692/anudeep-samaiya"
    # leetcode = "//leetcode.com/anudeepsamaiya"
    # linkedin = ""
    # instagram = ""
    # px500 = "//500px.com/anudeepsamaiya"

